-- Generated by hyprconf2lua v1.4.0
-- https://github.com/Prateek-squadron/hyprconf2lua
-- Manual review may be needed for complex directives

---@module 'hl'

--###########################

-- Variables

--###########################

local mod = "SUPER"

local alt = "ALT"

--###########################

-- Appearance

--###########################

hl.config({
	general = {
		border_size = 1,
		gaps_out = 0,
		gaps_in = 0,
		col = {
			active_border = "rgb(bf616a)",
			inactive_border = "rgb(2f343f)",
		},
	},
})

hl.config({
	decoration = {
		rounding = 0,
		blur = {
			enabled = false,
		},
		shadow = {
			enabled = false,
		},
	},
})

hl.animation({ leaf = "workspaces", enabled = 0 })

hl.animation({ leaf = "windows", enabled = 0 })

hl.animation({ leaf = "fade", enabled = 0 })

-- i3 font setting not directly supported globally in Hyprland

-- Configure fonts in your bar (e.g. waybar) instead

--###########################

-- Input

--###########################

-- Use SUPER + mouse to drag floating windows

hl.bind(mod .. " + " .. "mouse:272", hl.dsp.window.drag(), { mouse = true })

hl.bind(mod .. " + " .. "mouse:273", hl.dsp.window.resize(), { mouse = true })

hl.config({
	input = {
		accel_profile = "flat",
		force_no_accel = true,
	},
})

--###########################

-- Monitor

--###########################

hl.monitor({
	output = "DP-1",
	mode = "1920x1080@240",
	position = "0x0",
	scale = 1,
})

hl.monitor({
	output = "DP-2",
	mode = "1920x1080@240",
	position = "0x0",
	scale = 1,
})

--###########################

-- Autostart

--###########################

-- TODO: is this needed?

--###########################

-- Applications

--###########################

hl.bind(mod .. " + " .. "RETURN", hl.dsp.exec_cmd("ghostty"))

-- launcher

hl.bind(mod .. " + " .. "D", hl.dsp.exec_cmd("walker"))

-- lock

hl.bind(mod .. " + " .. "L", hl.dsp.exec_cmd("hyprlock"))

hl.bind(mod .. " + " .. "SHIFT" .. " + " .. "S", hl.dsp.exec_cmd('grim -g "$(slurp)"-| wl-copy'))

--###########################

-- Audio (PipeWire recommended)

--###########################

-- amixer (ALSA) works but wpctl is preferred for PipeWire

hl.bind("XF86AudioRaiseVolume", hl.dsp.exec_cmd("wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%+"))

hl.bind("XF86AudioLowerVolume", hl.dsp.exec_cmd("wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%-"))

hl.bind("XF86AudioMute", hl.dsp.exec_cmd("wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle"))

--###########################

-- Window Management

--###########################

hl.bind(mod .. " + " .. "Q", hl.dsp.window.close())

-- Music control (mpc works unchanged)

hl.bind("XF86AudioNext", hl.dsp.exec_cmd("mpc next"))

hl.bind("XF86AudioPrev", hl.dsp.exec_cmd("mpc prev"))

hl.bind("XF86AudioPlay", hl.dsp.exec_cmd("mpc toggle"))

hl.bind("XF86AudioStop", hl.dsp.exec_cmd("mpc stop"))

-- Focus movement

hl.bind(mod .. " + " .. "LEFT", hl.dsp.focus({ direction = "left" }))

hl.bind(mod .. " + " .. "RIGHT", hl.dsp.focus({ direction = "right" }))

hl.bind(mod .. " + " .. "UP", hl.dsp.focus({ direction = "up" }))

hl.bind(mod .. " + " .. "DOWN", hl.dsp.focus({ direction = "down" }))

-- Move windows

hl.bind(mod .. " + " .. "SHIFT" .. " + " .. "LEFT", hl.dsp.window.swap({ direction = "l" }))

hl.bind(mod .. " + " .. "SHIFT" .. " + " .. "RIGHT", hl.dsp.window.swap({ direction = "r" }))

hl.bind(mod .. " + " .. "SHIFT" .. " + " .. "UP", hl.dsp.window.swap({ direction = "u" }))

hl.bind(mod .. " + " .. "SHIFT" .. " + " .. "DOWN", hl.dsp.window.swap({ direction = "d" }))

-- Layouts

hl.bind(mod .. " + " .. "H", hl.dsp.layout("orientationleft"))

hl.bind(mod .. " + " .. "V", hl.dsp.layout("orientationtop"))

hl.bind(mod .. " + " .. "F", hl.dsp.window.fullscreen())

-- Toggle floating

hl.bind(mod .. " + " .. "SPACE", hl.dsp.window.float())

--###########################

-- Workspaces

--###########################

hl.bind(alt .. " + " .. "CTRL" .. " + " .. "RIGHT", hl.dsp.focus({ workspace = "e+1" }))

hl.bind(alt .. " + " .. "CTRL" .. " + " .. "LEFT", hl.dsp.focus({ workspace = "e-1" }))

hl.bind(mod .. " + " .. 1, hl.dsp.focus({ workspace = 1 }))

hl.bind(mod .. " + " .. 2, hl.dsp.focus({ workspace = 2 }))

hl.bind(mod .. " + " .. 3, hl.dsp.focus({ workspace = 3 }))

hl.bind(mod .. " + " .. 4, hl.dsp.focus({ workspace = 4 }))

hl.bind(mod .. " + " .. 5, hl.dsp.focus({ workspace = 5 }))

hl.bind(mod .. " + " .. 6, hl.dsp.focus({ workspace = 6 }))

hl.bind(mod .. " + " .. "SHIFT" .. " + " .. 1, hl.dsp.window.move({ workspace = 1 }))

hl.bind(mod .. " + " .. "SHIFT" .. " + " .. 2, hl.dsp.window.move({ workspace = 2 }))

hl.bind(mod .. " + " .. "SHIFT" .. " + " .. 3, hl.dsp.window.move({ workspace = 3 }))

hl.bind(mod .. " + " .. "SHIFT" .. " + " .. 4, hl.dsp.window.move({ workspace = 4 }))

hl.bind(mod .. " + " .. "SHIFT" .. " + " .. 5, hl.dsp.window.move({ workspace = 5 }))

hl.bind(mod .. " + " .. "SHIFT" .. " + " .. 6, hl.dsp.window.move({ workspace = 6 }))

--###########################

-- Resize mode (Hyprland has no i3-style mode blocks)

-- Use built-in resize dispatcher instead

--###########################

hl.bind(mod .. " + " .. "R", hl.dsp.submap("resize"))

hl.define_submap("resize", function()
	-- TODO: manual review (unknown dispatcher: resizeactive)
	-- hl.bind(" + LEFT", hl.dsp.resizeactive("-20 0"))
	-- TODO: manual review (unknown dispatcher: resizeactive)
	-- hl.bind(" + RIGHT", hl.dsp.resizeactive("20 0"))
	-- TODO: manual review (unknown dispatcher: resizeactive)
	-- hl.bind(" + UP", hl.dsp.resizeactive("0 -20"))
	-- TODO: manual review (unknown dispatcher: resizeactive)
	-- hl.bind(" + DOWN", hl.dsp.resizeactive("0 20"))
	hl.bind("RETURN", hl.dsp.submap("reset"))
end)

--###########################

-- Bar (i3bar → Waybar recommended)

--###########################

-- Hyprland does not provide a built-in bar.

-- Replace i3bar + i3status with Waybar.

--###########################

-- Window Rules (Wayland uses app_id instead of X11 class)

--###########################

-- You can inspect app_id using: hyprctl clients

-- TODO: Deprecated

--windowrulev2 = workspace 1, class:^(kitty)$

--windowrulev2 = workspace 2, class:^(code)$

--windowrulev2 = workspace 3, class:^(brave.*)$

--###########################

-- Restart Hyprland

--###########################

hl.bind(mod .. " + " .. "SHIFT" .. " + " .. "R", hl.dsp.exec_cmd("hyprctl reload"))

-- Autostart
hl.on("hyprland.start", function()
	hl.exec_cmd("hyprpaper")
	hl.exec_cmd("systemctl --user start elephant.service")
	hl.exec_cmd("mako")
	hl.exec_cmd("walker --gapplication-service")
	hl.exec_cmd("waybar")
	hl.exec_cmd("solaar --window hide")
end)
